const assert = require("assert")
const fs = require("fs")
const path = require("path")

const root = path.resolve(__dirname, "..")
const read = (p) => fs.readFileSync(path.join(root, p), "utf8")
const dashboard = read("media/dashboard.js")
const css = read("media/dashboard.css")
const i18n = read("media/i18n.js")
const dist = read("dist/extension.js")
const preview = read("test/make-preview.cjs")

assert.match(dashboard, /let currentView = api\.getState\(\)\?\.view === "accounts"/)
assert.match(dashboard, /const showAccounts = currentView === "accounts"/)
assert.doesNotMatch(dashboard, /addToggle\.classList\.toggle\("hidden"/)
assert.match(dashboard, /addToggle\.setAttribute\("aria-expanded", String\(show\)\)/)
assert.match(dashboard, /if \(e\.key === "Escape"\) els\.addToggle\.click\(\)/)
assert.doesNotMatch(dashboard, /models\.slice\(0, 8\)/)
assert.match(dashboard, /btn\.dataset\.context = String\(k \* 1024\)/)
assert.match(dashboard, /modelId\.replace\(\/\^\(\?:opencode-go\|opencode\)\\\/\//)
assert.match(dashboard, /model: configModelId\(modelId\), context/)
assert.match(dashboard, /chip = document\.createElement\(configurable \? "button" : "span"\)/)
assert.match(dashboard, /chip\.setAttribute\("aria-controls", contextRowId\(index\)\)/)
assert.match(dashboard, /chip\.addEventListener\("click", \(\) => focusContextModel\(id\)\)/)
assert.match(dashboard, /row\.scrollIntoView\(\{ behavior: reduceMotion \? "auto" : "smooth", block: "center" \}\)/)
assert.match(dashboard, /button\.setAttribute\("aria-current", "true"\)/)
assert.doesNotMatch(dashboard, /setTimeout\(\(\) => row\.classList\.remove\("targeted"\)/)
assert.match(dashboard, /row\.dataset\.modelId = modelId/)
assert.match(dashboard, /btn\.setAttribute\("aria-pressed", String\(current === k \* 1024\)\)/)
assert.match(dashboard, /<span class="usage-pct \$\{lvl\}">\$\{percent\.label\}<\/span>/)
assert.match(dashboard, /<svg class="bar-progress \$\{level\}"[^>]*role="progressbar"/)
assert.match(dashboard, /<rect class="bar-value"[^>]*width="\$\{percent\.barValue\}"/)
assert.match(dashboard, /aria-valuetext="\$\{escapeHtml\(valueText\)\}"/)
assert.match(dashboard, /progressBar\(w\.percent, levelFor\(w\.percent\.numeric, w\.usage\.status\)/)
assert.doesNotMatch(dashboard, /bar-fill|style="width:/)
assert.doesNotMatch(dashboard, /usageStats|renderLocalUsage|donutChart|DONUT_COLORS/)
assert.match(dashboard, /Number\.isFinite\(rawWarn\) \? rawWarn : 80/)
assert.match(dashboard, /Math\.max\(warn, Math\.min\(100, Number\.isFinite\(rawCrit\) \? rawCrit : 100\)\)/)

assert.match(css, /\.chips\s*\{[^}]*display:\s*flex;[^}]*flex-wrap:\s*wrap/s)
assert.match(css, /\.chip\s*\{[^}]*overflow-wrap:\s*anywhere/s)
assert.match(css, /button\.chip\s*\{[^}]*appearance:\s*none;[^}]*padding:\s*3px 6px/s)
assert.match(css, /button\.chip\[aria-current="true"\]\s*\{[^}]*background:/s)
assert.match(css, /button\.chip:focus-visible\s*\{[^}]*box-shadow:\s*inset/s)
assert.match(css, /@media \(forced-colors: active\)[\s\S]*button\.chip:focus-visible,[\s\S]*\.ctx-row:focus-visible\s*\{[^}]*outline:\s*2px solid Highlight;[^}]*outline-offset:\s*-3px/s)
assert.doesNotMatch(css, /button\.chip:hover\s*\{[^}]*text-decoration:\s*underline/s)
assert.doesNotMatch(css, /\.chip \+ \.chip::before/)
assert.match(css, /\.bar-progress\s*\{[^}]*--progress-color:\s*var\(--ok\)/s)
assert.match(css, /\.bar-progress\.warn\s*\{[^}]*--progress-color:\s*var\(--warn\)/s)
assert.match(css, /\.bar-progress\.crit\s*\{[^}]*--progress-color:\s*var\(--crit\)/s)
assert.match(css, /\.bar-progress \.bar-value\s*\{[^}]*var\(--progress-color\)/s)
assert.doesNotMatch(css, /::-webkit-progress-value|::-moz-progress-bar/)
assert.match(css, /#account-current\s*\{[^}]*text-overflow:\s*ellipsis/s)
assert.match(css, /#lang-dropdown\s*\{[^}]*position:\s*static/s)
assert.match(css, /\.account-actions\s*\{[^}]*display:\s*flex/s)
assert.doesNotMatch(css, /\.ls-|\.donut-|\.md-|\.session-/)
assert.doesNotMatch(dist, /scanLocalUsage|src\/localUsage\.ts|usageStats/)
assert.match(css, /\.ctx-opts\s*\{[^}]*display:\s*grid/s)
assert.match(css, /\.ctx-card\[open\] > summary::after/)

assert.match(dist, /<details id="ctx-card" class="panel ctx-card hidden">/)
assert.doesNotMatch(dist, /<section id="ctx-card" class="panel hidden">/)
assert.match(dist, /id="btn-add-toggle"[^>]*aria-expanded="false"/)
assert.doesNotMatch(dist, /id="local-card"|usage\.localTitle|usage\.localNote/)
assert.doesNotMatch(dist, /opencodeGo\.limits|usage\.amount/)
assert.doesNotMatch(dist, /<[^>]+style="/)
assert.doesNotMatch(i18n, /\$10/)
assert.match(dist, /refreshGeneration = 0/)
assert.match(dist, /function normalizeUsage\(raw\)/)
assert.match(dist, /return \{ kind: "ok", usage: normalizeUsage\(res\.usage\) \}/)
assert.match(dist, /const rawPercent = Number\.isFinite\(active\.percent\) \? active\.percent : 0/)
assert.match(dist, /usageAccountId: patch\.usageAccountId !== void 0/)
assert.match(dist, /activeAccount: patch\.activeAccount !== void 0/)
assert.match(dist, /const warn = Math\.max\(0, Math\.min\(100, Number\.isFinite\(rawWarn\) \? rawWarn : 80\)\)/)
assert.match(dist, /crit: Math\.max\(warn, Math\.min\(100, Number\.isFinite\(rawCrit\) \? rawCrit : 100\)\)/)
assert.match(dist, /<p class="muted">\$\{tr\("accounts\.hint"\)\}<\/p>/)
assert.doesNotMatch(preview, /\$10|额度占比|套餐总览/)
assert.match(preview, /usageAccountId: "a1"/)
assert.match(preview, /notifySettings: \{ enabled: true, warn: 50, crit: 70 \}/)

const expectedHints = [
  "手动添加的 key 保存在 VS Code 密钥存储中，仅本机可用。",
  "手動新增的 key 保存在 VS Code 密鑰儲存中，僅本機可用。",
  "Manually added keys are stored in VS Code's secret storage on this machine.",
  "수동으로 추가한 키는 이 기기의 VS Code 시크릿 저장소에 저장됩니다.",
  "手動で追加したキーはこのマシンの VS Code シークレットストレージに保存されます。",
]
for (const hint of expectedHints) {
  assert.ok(i18n.includes(hint), `missing webview hint: ${hint}`)
  assert.ok(dist.includes(hint), `missing bundled hint: ${hint}`)
}
assert.doesNotMatch(i18n, /Local[\s\S]{0,80}auth\.json|本机」账户来自|ローカル」アカウント/)

const keyReport = require(path.join(root, "media/i18n.js")).keys()
for (const [lang, missing] of Object.entries(keyReport.complete)) {
  assert.deepStrictEqual(missing, [], `missing i18n keys for ${lang}: ${missing.join(", ")}`)
}

console.log("ui-static: all assertions passed")
